name: CI/CD to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE: vuongdtxq/user

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push image to DockerHub
      run: |
        docker build -t $IMAGE:${{ github.sha }} .
        docker push $IMAGE:${{ github.sha }}

    - name: Authenticate to GKE
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GKE_CREDENTIALS }}

    - name: Set up GKE kubectl
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - name: Update Deployment on GKE
      run: |
        echo "Updating image to $IMAGE:${{ github.sha }}"
        kubectl set image deployment/user-app user=$IMAGE:${{ github.sha }}
